### ISSUE TITLE
Off canvas

### ISSUE THREAD

**Issue by greggmojica** [aewebsolutions/rcrop#1]
Hello - I am using a basic implementation of rcrop and it is always cropping off the image canvas when I move it. Why would this occur? Advice would be appreciated!

**Comment by aewebsolutions** [comment]
Sorry, I don't understand the issue. Please, explain yourself again. Also, have you seen these examples?Maybe they could help you:

- https://rawgit.com/aewebsolutions/rcrop/master/demos/basic.html
- https://rawgit.com/aewebsolutions/rcrop/master/demos/advanced.html

**Comment by 1der1** [comment]
I made a video which shows the problem:
https://www.youtube.com/watch?v=xb5DYNIuGZY&feature=youtu.be

As soon as you move the selection, the values for width and height go down.

It's worse the smaller the canvas is compared to the original picture.

I assume it is due to rounding when using the width and height values from the canvas,

**Comment by aewebsolutions** [comment]
Please, give me a link to inspect. I've seen the video but I have no clue when and where this issue has place. As you can see, first advance demo (https://rawgit.com/aewebsolutions/rcrop/master/demos/advanced.html) has no problem at all.

**Comment by 1der1** [comment]
Use a huge picture on a responsive page, then make the page as small as possible. This should be enough to reproduce the problem.

The video is a demo for 1der1. I only noticed the problem, when I made the video and I had to make everything small enough to fit into the video.

You can check it yourself here:
https://1der1.com/pages/update

(it requires a free registration)

**Comment by 1der1** [comment]
I checked the demo page again: If you make the window width as small as possible, you will see the value for width changing as soon as you move the selection.

**Comment by aewebsolutions** [comment]
Yes, you are right, I've seen it. When you asign a value by resize method or when you resize window and then move crop area, width and height are calculated again, but now from crop area, and values are rounded. So, crop change. I have to think how to fix this issue.

**Comment by 1der1** [comment]
Thank you so much, rcrop is just awesome. I tried the other crop plugins as well, but rcrop is the best.

**Comment by 1der1** [comment]
Why recalculate width and height at all? The moving never changes width and height. So you could do just nothing or set the crop area from the values you have. If required, you can still calculate x & y from the crop area,

**Comment by 1der1** [comment]
Another video, about the flexibility of rcrop: https://www.youtube.com/watch?v=rHI8ZvYN5Ek

**Comment by aewebsolutions** [comment]
Bugs have been fixed!

**Comment by 1der1** [comment]
Thank you so much for your prompt fix, Ángel Espro. 

rcrop is just the best cropping tool. I installed several other well-known croppers, but they all had major issues. I am glad I finally found rcrop. It has everything you need and the programming is very lean, clean and clever as well.

**Comment by aewebsolutions** [comment]
Thank you so much for your words!
