### ISSUE TITLE
[REQUEST] Setting aspect ratio via settings

### ISSUE THREAD

**Issue by tobiratzberger** [aewebsolutions/rcrop#10]
Hello, would it be possible to set aspect ratio in settings?

Like: aspectRatio: {1,1}

**Comment by aewebsolutions** [comment]
Hi. Yes. See Options: minSize and preserveAspectRatio

**Comment by tobiratzberger** [comment]
No. I would like to set them like 16:9 or 4:3

**Comment by aewebsolutions** [comment]
As I told you, use preserveAspectRatio and minSize to define aspect ratio. `minSize: [160, 90]` or `minSize: [80, 45]` imply 16:9

**Comment by tobiratzberger** [comment]
thank you!
