### ISSUE TITLE
Not usable for all images, why?

### ISSUE THREAD

**Issue by tobiratzberger** [aewebsolutions/rcrop#12]
Hello, the rcrop is not working for all images (from a different page)

For example: "https://www.jqueryscript.net/images/Animated-Firefly-Effect.jpg" does not work...
But "https://images.pexels.com/photos/127073/pexels-photo-127073.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260" does...

What to do here?

**Comment by aewebsolutions** [comment]
Share a fiddle

**Comment by tobiratzberger** [comment]
Its because the plugin need Access-Control-Allow-Origin Header set to the domain or *. rcrop needs to access the responsebdody
