### ISSUE TITLE
Bootstrap 4 in modal: doesn't show a default crop area

### ISSUE THREAD

**Issue by websiteproduct** [aewebsolutions/rcrop#13]
Doesn't show a default crop area in a modal window. In common page is working fine.

**Comment by aewebsolutions** [comment]
Hi! Share a fiddle

**Comment by 1der1** [comment]
I have no issues at all. Works perfectly on 1der1.com

**Comment by websiteproduct** [comment]
@aewebsolutions Hi! https://jsfiddle.net/8ay9zqk2/

**Comment by aewebsolutions** [comment]
There is no issue here. Image must be visible when plugin is initialized. So, you might do something like call it when modal is opened:

```js
$('#mymodal').one('shown.bs.modal', function (e) {
    $('#myimage').rcrop();
})
```
https://jsfiddle.net/8ay9zqk2/6/
