### ISSUE TITLE
Support For Touch events 

### ISSUE THREAD

**Issue by makerlabs** [aewebsolutions/rcrop#3]
Im a little confused does your cropping solution support touch events? I checked the code and there are touch events defined but the crop doesn't seem to respond to touch events at all...

**Comment by makerlabs** [comment]
OK I found the problem :)
Line https://github.com/aewebsolutions/rcrop/blob/master/src/js/rcrop.js#L1467 was causing the issue after removing it everything works fine.

**Comment by aewebsolutions** [comment]
Bugs have been fixed
