### ISSUE TITLE
not working selection area into mobile devices

### ISSUE THREAD

**Issue by sharmasaurabh1** [aewebsolutions/rcrop#4]
Hi Team,

Great job for the responsive crop feature, but selection area is not working in the mobile devices.

I want to crop by mobile, but it is unable to drag the selection area.

Please suggest and reply me ASAP.

Kind Regards

**Comment by aewebsolutions** [comment]
Hi! I will study and fix this you are commenting.
Thanks!

**Comment by aewebsolutions** [comment]
Bugs have been fixed
